controller:
  service:
    nodePorts:
      http: 32080
      https: 32443
  podAnnotations:
    "prometheus.io/scrape": true
    "prometheus.io/port": 10254
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: prometheus
      enabled: true